"""Contains default values."""

ROOT_DIR = "/usr/local/raa"
WIRELESS_IFACE = "wlan0"
WIRED_IFACE = "eth0"
CHUNK_SIZE = 1024**2
SSID = "raatest"
DATA_SERVER_LISTEN_PORT = 8000
CHUNKS = 10
SUT = ""
GENERATE_PCAP = True
GENERATE_REPORT = True
UPLOAD_CHUNKS = False
DOWNLOAD_CHUNKS = True
UPLOAD_DATA_SERVER_IP = ""
UPLOAD_DATA_SERVER_PORT = 10000
DOWNLOAD_DATA_SERVER_IP = ""
DOWNLOAD_DATA_SERVER_PORT = 10000
